name: "Push to docker hub"

on:
  push:
    branches: [master]

jobs:
  push_to_registry:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v2

      - name: Publish docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t handrywahyudi/goapp:latest .
          docker push handrywahyudi/goapp:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/linux/Documents/web-example-golang
            ls -lah
            docker rm -f web-goapp && docker rmi handrywahyudi/goapp:latest
            docker-compose -f docker-compose.yml up -d

    
  