name: "GitLeaks"

on: 
  push: 
    branches: [main, master, staging]
  pull_request:
    branches: [master]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master